-- BUNYAMIN FUAT YILDIZ, 
-- DBMS130  M02 Hands-On Lab Assignment Constructing the Database,
-- 01-27-2024 TIME 10:30 PM



--B CREATING TABLES

CREATE TABLE CUSTOMERS(
    CUSTOMER_ID NUMBER(6) NOT NULL,
    FIRST_NAME VARCHAR2(25) NOT NULL,
    LAST_NAME VARCHAR2(25) NOT NULL,
    STREET_ADDRESS VARCHAR2(50) NOT NULL,
    CITY VARCHAR2(50) NOT NULL ,
    STATE VARCHAR2(50) NOT NULL ,
    ZIP_CODE VARCHAR2(10) NOT NULL,
    COUNTRY CHAR(50),
    PHONE_NUMBER VARCHAR2(25),
    EMAIL_ADDRESS VARCHAR2(50),
	DATE_OF_BIRTH DATE,
	GENDER CHAR(1)
);

CREATE TABLE BOOKS(
    BOOK_ID NUMBER(6) NOT NULL,
    BOOK_TITLE VARCHAR2(250) NOT NULL,
    BOOK_DESCRIPTION VARCHAR2(2000),
    BOOK_CATEGORY_CD CHAR(2) NOT NULL,
    BOOK_PRICE NUMBER(8,2),
    BOOK_REVIEWS NUMBER(5),
    USER_RATING NUMBER(2,1)
);


CREATE TABLE BOOK_CATEGORY (
    BOOK_CATEGORY_CD CHAR(2) NOT NULL,
    BOOK_CATEGORY_NAME VARCHAR2(100) NOT NULL, 
    BOOK_CATEGORY_DESCRIPTION VARCHAR2(2000)
 );

CREATE TABLE ORDERS(
    ORDER_NBR NUMBER(12) NOT NULL,
    CUSTOMER_ID NUMBER(6) NOT NULL,
    ORDER_DATE TIMESTAMP NOT NULL,
    SALESPERSON_ID NUMBER(6)
);

CREATE TABLE ORDER_ITEMS(
    ORDER_ITEM_ID NUMBER(20) NOT NULL,
    ORDER_NBR  NUMBER(12) NOT NULL,
    BOOK_ID NUMBER(6) NOT NULL,
    UNIT_PRICE NUMBER(8,2),
    QUANTITY NUMBER(8)
);



--C CREATING CONSTRAINTS

-- 1 ADDING USED SALTER TABLE statements to add primary key constraints  to tables  created in step 1

ALTER TABLE CUSTOMERS
ADD CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID);

ALTER TABLE BOOKS
ADD CONSTRAINT PK_BOOKS PRIMARY KEY (BOOK_ID);

ALTER TABLE BOOK_CATEGORY 
ADD CONSTRAINT PK_BOOK_CATEGORY_CD PRIMARY KEY (BOOK_CATEGORY_CD);

ALTER TABLE ORDERS
ADD CONSTRAINT PK_ORDERS PRIMARY KEY(ORDER_NBR);

ALTER TABLE ORDER_ITEMS
ADD CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ITEM_ID);



-- 2 ALTER TABLE statements to add foreign key constraints to tables  created in step 1
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORD_CUST
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID);

ALTER TABLE ORDER_ITEMS
ADD CONSTRAINT FK_ORD_ITEM_ORD
FOREIGN KEY (ORDER_NBR) REFERENCES ORDERS(ORDER_NBR);

ALTER TABLE ORDER_ITEMS
ADD CONSTRAINT FK_ORD_ITEM_PROD
FOREIGN KEY (BOOK_ID) REFERENCES BOOKS(BOOK_ID);

ALTER TABLE BOOKS 
ADD CONSTRAINT FK_BOOK_BOOK_CAT
FOREIGN KEY (BOOK_CATEGORY_CD) REFERENCES BOOK_CATEGORY(BOOK_CATEGORY_CD);




--3 add a foreign key constraint for the relationship between the EMPLOYEES table  and the ORDERS table.
ALTER TABLE ORDERS
ADD CONSTRAINT FK_ORDERS_EMPLOYEES
FOREIGN KEY (SALESPERSON_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);




-- 4 4.	Write an ALTER TABLE statement to add a unique constraint on the ORDER_ITEMS table that includes ORDER_NBR and BOOK_ID.
ALTER TABLE ORDER_ITEMS
ADD CONSTRAINT UK_ORDER_ITEMS UNIQUE (ORDER_NBR, BOOK_ID);





/*
   CREATE TABLE ORDER_ITEMS(
      ORDER_ITEM_ID NUMBER(20) NOT NULL,
      ORDER_NBR NUMBER(12) NOT NULL,
      BOOK_ID NUMBER(6) NOT NULL,
      UNIT_PRICE NUMBER(8,2),
      QUANTITY NUMBER(8),
      CONSTRAINT PK_ORDER_ITEMS PRIMARY KEY (ORDER_ITEM_ID),
      CONSTRAINT FK_ORD_ITEM_ORD FOREIGN KEY (ORDER_NBR) 
      REFERENCES ORDERS(ORDER_NBR),
      CONSTRAINT FK_ORD_ITEM_PROD FOREIGN KEY (BOOK_ID) 
      REFERENCES BOOKS(BOOK_ID)
   );
*/

