-- Name: BUNYAMIN FUAT YILDIZ
-- Assignment: DBMS130 – M03 Hands-On Lab Assignments Inserting and Modifying Data and Writing Simple Queries
-- Date: 02-09-2024


/*  PART B

-- --------------------------------------------------------------------------------------------------
--	INSERT DATA INTO TABLES
-- --------------------------------------------------------------------------------------------------

--	POPULATE BOOK_CATEGORY TABLE
INSERT INTO BOOK_CATEGORY(BOOK_CATEGORY_CD,BOOK_CATEGORY_NAME)
    VALUES('F','Fiction');
INSERT INTO BOOK_CATEGORY(BOOK_CATEGORY_CD,BOOK_CATEGORY_NAME)
    VALUES('NF','Non-Fiction');

--	POPULATE BOOKS TABLE
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(203351,'Act Like a Lady, Think Like a Man: What Men Really Think About Love, Relationships, Intimacy, and Commitment','NF',17,5013,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(385966,'Arguing with Idiots: How to Stop Small Minds and Big Government','NF',5,798,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(550196,'Breaking Dawn (The Twilight Saga, Book 4)','F',13,9769,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(537557,'Crazy Love: Overwhelmed by a Relentless God','NF',14,1542,4.7);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(261616,'Dead And Gone: A Sookie Stackhouse Novel (Sookie Stackhouse/True Blood)','F',4,1541,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(42039,'Diary of a Wimpy Kid: The Last Straw (Book 3)','F',15,3837,4.8);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(189634,'Divine Soul Mind Body Healing and Transmission System: The Divine Way to Heal You, Humanity, Mother Earth, and Allâ€¦','NF',6,37,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(644410,'Dog Days (Diary of a Wimpy Kid, Book 4) (Volume 4)','F',12,3181,4.8);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(70003,'Eat This Not That! Supermarket Survival Guide: The No-Diet Weight Loss Solution','NF',1,720,4.5);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(125306,'Eat This, Not That! Thousands of Simple Food Swaps that Can Save You 10, 20, 30 Pounds--or More!','NF',14,956,4.3);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(467154,'Eclipse (Twilight Sagas)','F',7,5505,4.7);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(959505,'Eclipse (Twilight)','F',18,5505,4.7);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(23734,'Glenn Becks Common Sense: The Case Against an Out-of-Control Government, Inspired by Thomas Paine','NF',11,1365,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(140044,'Going Rogue: An American Life','NF',6,1636,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(50322,'Good to Great: Why Some Companies Make the Leap and Others Dont','NF',14,3457,4.5);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(988563,'Have a Little Faith: A True Story','NF',4,1930,4.8);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(650799,'I, Alex Cross','F',7,1320,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(963312,'Liberty and Tyranny: A Conservative Manifesto','NF',15,3828,4.8);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(967488,'Mastering the Art of French Cooking, Vol. 2','NF',27,2926,4.8);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(551164,'New Moon (The Twilight Saga)','F',10,5680,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(734907,'Olive Kitteridge','F',12,4519,4.2);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(875164,'Outliers: The Story of Success','NF',20,10426,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(719660,'Publication Manual of the American Psychological Association, 6th Edition','NF',46,8580,4.5);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(981311,'Sookie Stackhouse','F',25,973,4.7);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(755002,'StrengthsFinder 2.0','NF',17,5069,4);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(693371,'Super Freakonomics: Global Cooling, Patriotic Prostitutes, and Why Suicide Bombers Should Buy Life Insurance','NF',18,1583,4.5);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(712303,'The 5000 Year Leap','NF',12,1680,4.8);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(163776,'The 7 Habits of Highly Effective People: Powerful Lessons in Personal Change','NF',24,9325,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(188113,'The Book of Basketball: The NBA According to The Sports Guy','NF',53,858,4.7);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(527711,'The Elegance of the Hedgehog','F',11,1859,4);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(966705,'The Five Dysfunctions of a Team: A Leadership Fable','NF',6,3207,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(372897,'The Five Love Languages: How to Express Heartfelt Commitment to Your Mate','NF',9,803,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(527086,'The Girl Who Played with Fire (Millennium)','F',16,7251,4.7);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(411086,'The Girl with the Dragon Tattoo (Millennium Series)','F',2,10559,4.4);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(373086,'The Guernsey Literary and Potato Peel Pie Society','F',10,8587,4.7);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(375189,'The Help','F',6,13871,4.8);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(117356,'The Last Lecture','NF',9,4028,4.7);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(159258,'The Last Olympian (Percy Jackson and the Olympians, Book 5)','F',7,4628,4.8);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(53434,'The Lost Symbol','F',19,8747,4.2);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(89096,'The Love Dare','NF',13,1655,4.8);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(384093,'The Shack: Where Tragedy Confronts Eternity','F',8,19720,4.6);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(456618,'The Time Travelers Wife','F',6,3759,4.4);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(403678,'The Tipping Point: How Little Things Can Make a Big Difference','NF',9,3503,4.4);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(524336,'The Twilight Saga Collection','F',82,3801,4.7);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(783056,'Three Cups of Tea: One Mans Mission to Promote Peace - One School at a Time','NF',11,3319,4.3);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(386905,'True Compass: A Memoir','NF',15,438,4.5);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(339453,'Twilight (The Twilight Saga, Book 1)','F',9,11676,4.7);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(251164,'Under the Dome: A Novel','F',20,6740,4.3);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(286413,'Watchmen','F',42,3829,4.8);
INSERT INTO BOOKS(BOOK_ID,BOOK_TITLE,BOOK_CATEGORY_CD,BOOK_PRICE,BOOK_REVIEWS,USER_RATING)
	VALUES(124600,'Where the Wild Things Are','F',13,9967,4.8);
*/
--PART C.	UPDATE Statements (5 points)
-- 1a.	Fredrick Tewkesbury

UPDATE CUSTOMERS
SET DATE_OF_BIRTH = '1996-06-12'
WHERE CUSTOMER_ID = 312;

--1b update US
UPDATE CUSTOMERS
SET COUNTRY = 'US'
WHERE COUNTRY = 'United States';

--1c.	Ellen Abel (EMPLOYEE_ID 174) \
UPDATE EMPLOYEES
SET JOB_ID = 'SA_MAN',
    SALARY = 15099,
    MANAGER_ID = 100
WHERE EMPLOYEE_ID = 174;

--1dd.	A few employees received raises. Write UPDATE statements Their employee IDs and new salary amounts are listed below.	143 – New salary = 2753  and 144 – New salary = 2653

UPDATE EMPLOYEES
SET SALARY = 2753
WHERE EMPLOYEE_ID = 143;

UPDATE EMPLOYEES
SET SALARY = 2653
WHERE EMPLOYEE_ID = 144;




---PART D DELETE STATEMENTS



--1A DELETE TWO BOOKS  981311 AND  373086


DELETE FROM BOOKS
WHERE BOOK_ID = 981311 OR BOOK_ID = 373086;


--1B- DELET CUSTOMER 385

DELETE FROM CUSTOMERS
WHERE customer_id = 385;


--E 

-- Name: BUNYAMIN FUAT YILDIZ
-- Assignment: DBMS130 – M03 Hands-On Lab Assignments Inserting and Modifying Data and Writing Simple Queries
-- Date: 02-09-2024




--F SECTION
--A
SELECT * FROM CUSTOMERS; -- RETRIEVES ALL COLUMNS FROM CUSTOMER TABLE


--b.	Write a query to display customers’ first names, last names, and email addresses.
SELECT FIRST_NAME, LAST_NAME, EMAIL
FROM CUSTOMERS;




--C CONCAT FIRSTNAME AND LASTNAME 
SELECT FIRST_NAME ||' '|| LAST_NAME 
FROM CUSTOMERS;


--D ALIAS


SELECT FIRST_NAME || ' ' || LAST_NAME AS "CUSTOMER FULL NAME"
FROM CUSTOMERS;


--E  Sentence build
SELECT 'The customer ' || FIRST_NAME || ' ' || LAST_NAME || ' can be reached at the email address ' || EMAIL AS "CUSTOMER INFORMATION"
FROM CUSTOMERS;



--F.	
--1a SELECT * FROM CUSTOMERS what it means Answer : It selects all columns from CUSTOMERS Table. 
-- 1b Write a query that displays a list of employees’ IDs, names, salary, and salary with a 5% increase.

SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME AS "NAME", SALARY, SALARY * 1.05 AS "SALARY_WITH_5_INCREASE"
FROM EMPLOYEES;
--1c concatenation operator ( || ) to concatenate the customers’ first and last names 
SELECT FIRST_NAME ||' '|| LAST_NAME 
FROM CUSTOMERS;
--1d
SELECT FIRST_NAME || ' ' || LAST_NAME AS "CUSTOMER FULL NAME"
FROM CUSTOMERS;
--1e
SELECT 'The customer ' || FIRST_NAME || ' ' || LAST_NAME || ' can be reached at the email address ' || EMAIL AS "CUSTOMER INFORMATION"
FROM CUSTOMERS;

--1f
SELECT EMPLOYEE_ID, FIRST_NAME || ' ' || LAST_NAME AS "NAME", SALARY, SALARY * 1.05 AS "SALARY_WITH_5_INCREASE"
FROM EMPLOYEES;

-- PART  ORDER BY STATEMENTS


--G
SELECT FIRST_NAME || ' ' || LAST_NAME AS "CUSTOMER FULL NAME"
FROM CUSTOMERS
ORDER BY "CUSTOMER FULL NAME" DESC;

--H MOST RECENT HIRED
SELECT *
FROM EMPLOYEES
ORDER BY HIRE_DATE DESC;

--I Display the results so that departments are sorted in ascending order and the employees with the highest salaries display before those with lower salaries.

SELECT *
FROM EMPLOYEES
ORDER BY DEPARTMENT ASC, SALARY DESC;

--J
SELECT DISTINCT CUSTOMER_ID
FROM ORDERS;

--WHERE
--K work in the marketing department (DEPARTMENT_ID 20
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 20
ORDER BY LAST_NAME;

--L salaries higher than $10,000. Sort the results so that the highest salary displays first.

SELECT *
FROM EMPLOYEES
WHERE SALARY > 10000
ORDER BY SALARY DESC;


--M to display the names and email addresses of the employees 
--hired on 07-JUN-94. Sort the results by the employees’ last names.
SELECT FIRST_NAME, LAST_NAME, EMAIL
FROM EMPLOYEES
WHERE HIRE_DATE = TO_DATE('07-JUN-94', 'DD-MON-YY')
ORDER BY LAST_NAME;


--N  phone numbers of the employees with area codes (1st 3 digits) of 650. Sort 

SELECT FIRST_NAME, LAST_NAME, PHONE_NUMBER
FROM EMPLOYEES
WHERE PHONE_NUMBER LIKE '650%'
ORDER BY LAST_NAME;


--O last names begin with the letter ’H’. Sort the results by the employees’ last names.

SELECT *
FROM EMPLOYEES
WHERE LAST_NAME LIKE 'H%'
ORDER BY LAST_NAME;


--P  WHERE DEPARTMENT_ID = 80 AND SALARY > 5000
SELECT *
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 80 AND SALARY > 5000
ORDER BY LAST_NAME ASC, SALARY DESC;


--Q (DEPARTMENT_IDs 20 and 80) and have a salary between $5,000 and $10,000. Sort 

SELECT *
FROM EMPLOYEES
WHERE (DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 80)
  AND SALARY >= 5000 AND SALARY <= 10000
ORDER BY LAST_NAME ASC, SALARY DESC;

--R REWRITE WITH BETWEEN

SELECT *
FROM EMPLOYEES
WHERE (DEPARTMENT_ID = 20 OR DEPARTMENT_ID = 80)
  AND SALARY BETWEEN 5000 AND 10000
ORDER BY LAST_NAME ASC, SALARY DESC;


--S(DEPARTMENT_IDs 20 and 80). Sort the results by department and the employees’ last names.
SELECT FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (20, 80)
ORDER BY DEPARTMENT_ID ASC, LAST_NAME ASC;

--T NOT IN SALEES MARKETING 


SELECT FIRST_NAME, LAST_NAME, JOB_ID, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID NOT IN (20, 80)
ORDER BY DEPARTMENT_ID ASC, LAST_NAME ASC;
